<?php

namespace Computer\Model;

/**
 * Class ImagesModel
 * @package Computer\Model
 */

class ImagesModel extends CommonModel
{
    protected $resource_path_old;
    public function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        $data['create_time'] = $data['update_time'] = time();
    }

    public function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        $data['update_time'] = time();
    }

    public function _before_delete($options)
    {
        $this->resource_path_old = $this->where($options['where'])->getField('resource',true);
        parent::_before_delete($options); // TODO: Change the autogenerated stub
    }

    public function _after_delete($data, $options)
    {
        parent::_after_delete($data, $options); // TODO: Change the autogenerated stub
        foreach ($this->resource_path_old as $file){
            if(file_exists($file)){
                unlink($file);
            }
        }
    }
}