<?php

namespace Computer\Model;

/**
 * Class ShopModel
 * @package Computer\Model
 */
class ShopModel extends CommonModel
{
    public function __call($method, $args)
    {
        //return parent::__call($method, $args); // TODO: Change the autogenerated stub
        if(substr($method,7) == 'comment') {
            var_dump(D('Comment'));die;
            return D('Comment')->$method($args[0]);
        }
    }
}