<?php

namespace Computer\Model;

/**
 * Class ShopModel
 * @package Computer\Model
 */
class ShopModel extends CommonModel
{
    public function __call($method, $args)
    {
        if(substr($method,0,7) == 'comment') {
            return D('Comment')->$method($args[0]);
        }
        return parent::__call($method, $args); // TODO: Change the autogenerated stub
    }
}