<?php

namespace Common\Model;

/**
 * Class AddressModel
 * @package Common\Model
 */
class AddressModel extends CommonModel
{
    public function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        $data['create_time'] = time();
        $data['update_time'] = time();
    }

    public function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        $data['update_time'] = time();
    }
    public function _after_db()
    {
        parent::_after_db(); // TODO: Change the autogenerated stub
    }

    public function _after_setField($data)
    {
        var_dump(15441544);
    }

}