<?php

namespace Common\Model;

/**
 * Class Collect
 * @package Common\Model
 * 收藏模型库
 */

class CollectModel extends CommonModel
{
    protected $_link = [
        'shop'=> [
            'mapping_type'  => self::BELONGS_TO,
            'class_name'    => 'shop',
            'foreign_key'   => 's_id',
            'as_fields'     => 'img,tit,tit_en,price,rate'
        ],
    ];

    protected $_map = [
        //'表单' => '字段名'
    ];

    public function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        $data['create_time'] = time();
    }

    public function getList($id){
        $list = $this->field(['id','s_id'])->where(['u_id'=>$id])->relation('shop')->limit($this->page())->select();
//        foreach ($list as $key=>$item) {
//            $list[$key]['id']  = url_encode($item['id']);
//            $list[$key]['s_id']  = url_encode($item['s_id']);
//        }
        return $list;
    }

    public function addCollect($UserID,$ShopID){
        return $this->add(['u_id'=>$UserID,'s_id'=>$ShopID]);
    }

    public function removeCollect($UserID,$ShopID){
        return $this->where(['u_id'=>$UserID,'s_id'=>$ShopID])->limit(1)->delete();
    }
}