<?php

namespace Common\Model;

/**
 * Class ShopModel
 * @package Common\Model
 * 商品模型
 */

class ShopModel extends CommonModel
{
    public function getShopInfoMin($shopId){
        return $this->field('id,img,tit')->find($shopId);
    }

    public function __call($method, $args)
    {
        if(substr($method,0,7) == 'comment') {
            return D('Comment')->$method($args[0]);
        }
        return parent::__call($method, $args); // TODO: Change the autogenerated stub
    }
}