<?php

namespace Service\Model;
use Think\Model;

/**
 * Class AddressModel
 * @package Common\Model
 */
class AddressModel extends Model
{
    public $Error = null;
    protected $_map = [
        'default' => 'sdefault',
        'name' => 'sname',
        'tel' => 'siphone',
        'address' => 'saddress',
    ];
    public function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        if(!is_null($this->Error)) return false;
        $address_count = $this->where(['user_id'=>$data['user_id']])->count();
        if($address_count >= 20) {
            $this->Error = '最多添加20条收货地址！';
            return false;
        }
        if(isset($data['sdefault']) && $data['sdefault'] == '1'){
            $this->where(['user_id'=>$data['user_id']])->setField('sdefault','0');
        }
        $data['create_time'] = time();
        $data['update_time'] = time();
    }

    public function _before_write(&$data)
    {
        parent::_before_write($data); // TODO: Change the autogenerated stub
        if(isset($data['siphone'])){
            if(!is_mobile($data['siphone'])){
                $this->Error = '请输入正确的手机号！';
                return false;
            }
        }
    }

    public function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        if(!is_null($this->Error)) return false;
        $data['update_time'] = time();
    }

    public function checkFields($data){
        $checkFields = ['sname','siphone','saddress','daddress'];
        foreach ($checkFields as $key){
            if(empty($data[$key])) {
                $this->Error = '缺少必要的参数！';
                return false;
            }
        }
        return true;
    }

    public function setDefault(array $where){
        $res = $this->where($where)->find();
        if(empty($res)) return false;
        $res = $this->where(array_merge($where,['sdefault'=>'1']))->find();
        if(!empty($res)) return true;
        $this->startTrans();
        $delDefault = $this->where(['user_id'=>$where['user_id'],'sdefault'=>'1'])->setField('sdefault','0');
        $setDefault = $this->where($where)->setField('sdefault','1');
        if($delDefault === false || $setDefault === false){
            $this->rollback();
            return false;
        }else{
            $this->commit();
            return true;
        }
    }
}