<?php
namespace Common\Controller;

/**
 * 商品详情接口
 */
class ShopController extends CommonController
{
    private $actions = ['commentlist'=>'list','commentadd'=>'add','commentremove'=>'remove'/*,'commentupdate'=>'update'*/];
    private $data;
    private $message;
    public function comment($type = 'list'){
        $type= strtolower($type);
        if(!in_array($type,$this->actions)) $this->quickReturn(false,'错误操作！');
        $method = __FUNCTION__.ucfirst($type);
        $res = $this->Model->$method($this);
        if($res){
            $this->returnAjaxSuccess(['message'=>$this->message,'data'=>$this->data]);
        }else{
            $this->returnAjaxError(['message'=>$this->message]);
        }
    }

    public function _empty($method, $args)
    {
        $type = strtolower($method);
        if(array_key_exists($type,$this->actions)){
            $this->comment($this->actions[$type]);
        }else{
            parent::_empty(); // TODO: Change the autogenerated stub
        }
    }
}