<?php
namespace Computer\Controller;

class ShopController extends CommonController
{
    private $actions = ['list','add','remove','update'];
    private $data;
    private $message;
    public function comment($type = 'list',$shop = null){
        $type= strtolower($type);
        if(!in_array($type,$this->actions)) $this->quickReturn(false,'错误操作！');
        $method = __FUNCTION__.ucfirst($type);
        $res = $this->Model->$method($this);
        if($res){
            $this->returnAjaxSuccess(['message'=>$this->message,'data'=>$this->data]);
        }else{
            $this->returnAjaxError(['message'=>$this->message]);
        }
    }

    public function _empty($method, $args)
    {
        $type = strtolower($method);
        if(in_array($type,$this->actions)){
            $this->comment($type,I('request.shop',null));
        }else{
            parent::_empty(); // TODO: Change the autogenerated stub
        }
    }
}